### ISSUE TITLE
add separator, how to do?

### ISSUE THREAD

**Issue by wvmoreira** [dvinfosys/Android-Custom-Navigation-Drawer-Using-ExpandableListView#1]
Hi, thank you very much for the project. It will help me a lot! How can I place a divider? and a title above the divider As shown in the image below

https://i.stack.imgur.com/A1jDi.png
item "Communicate"

**Comment by dvinfosys** [comment]
@wvmoreira You can use multi time Navigation listview.

try this
 


        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="170dp">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

                <com.dvinfosys.ui.NavigationListView
                    android:id="@+id/expandable_navigation"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="left"
                    android:divider="@null"
                    android:groupIndicator="@null"
                    android:scrollbars="vertical" />

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1dp"
                    android:layout_marginTop="8dp"
                    android:background="@android:color/darker_gray" />

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="8dp"
                    android:layout_marginTop="8dp"
                    android:layout_marginBottom="8dp"
                    android:text="Communicate" />

                <com.dvinfosys.ui.NavigationListView
                    android:id="@+id/nlv_communicate"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="left"
                    android:divider="@null"
                    android:groupIndicator="@null"
                    android:scrollbars="vertical" />
            </LinearLayout>
        </ScrollView>

    

Java File


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
      
        NavigationListView listView = findViewById(R.id.expandable_navigation);
        NavigationListView nlvCommunicate = findViewById(R.id.nlv_communicate);

        nlvCommunicate.init(this)
                .addHeaderModel(new HeaderModel("Share", android.R.drawable.ic_menu_share))
                .addHeaderModel(new HeaderModel("Send", android.R.drawable.ic_menu_send))
                .build()
                .addOnGroupClickListener(new ExpandableListView.OnGroupClickListener() {
                    @Override
                    public boolean onGroupClick(ExpandableListView parent, View v, int groupPosition, long id) {
                        nlvCommunicate.setSelected(groupPosition);
                        if (id == 0){
                            Common.showToast(context, "App Share Clicked");
                            drawer.closeDrawer(GravityCompat.START);
                        }else if (id == 1){
                            Common.showToast(context, "App send Clicked");
                            drawer.closeDrawer(GravityCompat.START);
                        }
                        return false;
                    }
                });
    }

**Example**
![demo](https://user-images.githubusercontent.com/29920415/161561092-e9527938-4995-4fcf-83f9-24a146dc6f06.png)
